apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-notice-dep
  namespace: polyns
  labels:
    app: my-notice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-notice
      tier: backend
  template:
    metadata:
      name: my-notice
      labels:
        app: my-notice
        tier: backend
    spec:
      containers:
        - name: my-notice
          image: docker.io/hyeopgeonlee/notice3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 11000
      restartPolicy: Always
