apiVersion: v1
kind: Service
metadata:
  name: my-notice-svc
  namespace: polyns
  labels:
    app: my-notice
spec:
  selector:
    app: my-notice
    tier: backend
  ports:
    - protocol: TCP
      port: 11000
      targetPort: 11000
      nodePort: 31100
  type: NodePort